language: node_js
node_js:
  - 13  

services:
  - docker

# Assuming the .travis.yml file is in the project directory, and there is a separate sub-directory for each service
# Use either `docker-compose` or individual `docker build` commands
# Build
# Tagging
script:
  - docker build -t udagram-api-feed ./udagram-api-feed
  - docker tag udagram-api-feed moelmou/udagram-api-feed:v1
  - docker build -t udagram-api-feed ./udagram-api-user
  - docker tag udagram-api-user moelmou/udagram-api-user:v1
  - docker build -t udagram-api-feed ./udagram-reverseproxy
  - docker tag udagram-reverseproxy moelmou/udagram-reverseproxy:v1
  - docker build -t udagram-api-feed ./udagram-frontend
  - docker tag udagram-frontend moelmou/udagram-frontend:v1

# Push
# Assuming DOCKER_PASSWORD and DOCKER_USERNAME are set in the Travis repository settings
after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push sudkul/udagram-api-feed:v1
  - docker push sudkul/udagram-api-user:v1
  - docker push sudkul/udagram-reverseproxy:v1
  - docker push sudkul/udagram-frontend:v1