apiVersion: v1
kind: ConfigMap
metadata:
  name: aws-creds
data:
  credentials: |
    [default]
    aws_access_key_id = ASIAYY53LLEQWYVJDQ7G
    aws_secret_access_key = JPHWIDz/O+xrCsDnTlI/bHbvfBD4q8cGyyuNH/j1
    aws_session_token = FwoGZXIvYXdzEP3//////////wEaDGSjkrBbbazOMITNYCK8AcKAfYvWaCaTMeqI72SiwubP4dYbyymPhATeQ5h8pHd/qYesDW8kMzrPcg3Z+sR/Lv739rtGaJpsEsYo9DtHyEH6DNTPbRUiduJQF9/pLD27C79APZSTTKbln0oouVsoArpKp5+QbJ2AgBZo/sOTLTrBZGCFaxxT0I7N7nW9BvERdnSJiGx4xD0U+XWz11B27ejIiJZRcJF7eSvCvGfeXDJzB2rotp/qSzo48yvPU+rFOjy0WCUYVr5NLGsiKICZ65kGMi0NKOP8opoLtKOcyVfjdxtQ8NKK6rE+qvjNsd9IjJkBLbD83g93q8R4e53kUSU=