apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-user
  labels:
    app: backend-user
spec:
  replicas: 2
  selector:
    matchLabels:
      app: backend-user
  template:
    metadata:
      labels:
        app: backend-user
    spec:
      containers:
      - name: backend-user
        image: moelmou/udagram-api-user:v6
        ports:
        - containerPort: 8080
        envFrom:
        - configMapRef:
            name: env-configmap  
        - secretRef:
            name: env-pg-secrets
        volumeMounts:
        - name: aws-creds
          mountPath: "/root/.aws"
      volumes:
      - name: aws-creds
        configMap:
          name: aws-creds
