apiVersion: apps/v1
kind: Deployment
metadata:
  name:  backend-feed
  labels:
    app: backend-feed
spec:
  replicas: 2
  selector:
    matchLabels:
      app: feed
  template:
    metadata:
      labels:
        app: feed
    spec:
      containers:
      - name:  feed
        image: moelmou/udagram-api-feed:v6
        ports:
        - containerPort: 8080        
        envFrom:
        - configMapRef:
            name: env-configmap  
        - secretRef:
            name: env-pg-secrets
        volumeMounts:
        - name: aws-creds
          mountPath: "/root/.aws"
      volumes:
      - name: aws-creds
        configMap:
          name: aws-creds